<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-27T19:40:51 IST" name="Suite" finished-at="2023-05-27T19:40:59 IST" duration-ms="7461">
    <groups>
    </groups>
    <test started-at="2023-05-27T19:40:51 IST" name="Test" finished-at="2023-05-27T19:40:59 IST" duration-ms="7461">
      <class name="selefrmae.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:52 IST" name="launchApplication" finished-at="2023-05-27T19:40:55 IST" duration-ms="3390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErr()[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:55 IST" name="loginErr" finished-at="2023-05-27T19:40:55 IST" duration-ms="546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErr -->
        <test-method is-config="true" signature="CloseDriver()[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:55 IST" name="CloseDriver" finished-at="2023-05-27T19:40:56 IST" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDriver -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:56 IST" name="launchApplication" finished-at="2023-05-27T19:40:58 IST" duration-ms="1642" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="producvalidation(java.util.HashMap)[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:58 IST" name="producvalidation" data-provider="datainit" finished-at="2023-05-27T19:40:58 IST" duration-ms="922" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{name=standard_user, password=secret_sauce}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Sauce Labs Bike Light] but found [Sauce Labs Bike Light 44 ]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Sauce Labs Bike Light] but found [Sauce Labs Bike Light 44 ]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at selefrmae.ErrorValidationTest.producvalidation(ErrorValidationTest.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- producvalidation -->
        <test-method is-config="true" signature="CloseDriver()[pri:0, instance:selefrmae.ErrorValidationTest@27eedb64]" started-at="2023-05-27T19:40:59 IST" name="CloseDriver" finished-at="2023-05-27T19:40:59 IST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseDriver -->
      </class> <!-- selefrmae.ErrorValidationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
